envname: HuskyNavigateEnv # environment name, make sure it is the same as the class name of the env
model_id: space3 # choose space (scene)
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, 4.71] # model initial orientation [roll, pith, yaw]
initial_pos: [0, 7, 0.5] # model initial position [x, y, z]
fov: 1.57 # field of view for the camera
is_discrete: true

use_filler: true
display_ui: true # use pygame window or not
show_diagnostics: true
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor]
resolution: 256

speed:
  timestep: 0.001
  frameskip: 10

mode: gui #gui|headless # follow the robot true|false
verbose: false
